### ISSUE TITLE
Radegast keeps changing the contents of my Profile > Interests tab.

### ISSUE THREAD

**Issue by gaveitatry2** [radegastdev/radegast#65] opened 2022-02-15 03:34 UTC
**UPDATE:**

So I think that I found the issue.  While in Radegast, go to your Interests tab and uncheck all the boxes and type something that you want to do like "I want to fly."  Save and close your profile.  Now open it up again.  It will appear the same.  Now close it again.  Now open up some random profiles of other SL residents that you see Nearby.  Close their profiles.  Open up your profile.  Now the stuff you typed will be gone or replaced and there will be random boxes checked.  It's a Radegast thing and I don't get the point.  Like "ha ha"?  So hopefully I can keep my settings if I NEVER open up another SL resident's profile.  If not, then well, I give up.

And here is a three second video proving that Radegast is doing this:
https://youtu.be/MIVqdz6eJWs

**ORIGINAL:**

Hi.  When I am logged in SL on the Firestorm Viewer, I can change the information on my Interests tab.  What I usually do is uncheck all the checkboxes in "I Want To:" and "Skills:".  I put "English." under Languages.  And I write that "I really love adult sims, but I am not interested in SL sex."  I am sure that there are those who would put me down for caring what goes on my Interests tab or not, and for the content that I want to put on my Interests tab.  Hopefully they won't give me any grief.  The problem is that this information is constantly changing on it's own.  Every once in a while I will check it and there will be random checkboxes marked or some random text like "Time to meme it up."  I believe that this is because of Radegast.  I switch viewers sometimes when I don't want to graphics but still want to interact and be present in SL.  It gives my laptop time to cool down.  I believe that Radegast does things to my Interests tab and then when I log into the Firestorm Viewer, I eventually notice it later.  Is there a way to stop Radegast from doing this (and I don't mean stop using Radegast).  Sorry, I am not 100% familiar with Radegast and there might be an option to toggle this behavior off and I haven't found it yet.  If so, I apologize for not finding it on my own and relying on your help.  Hopefully you won't mind telling me how to make it stop.  Thank you.

**Comment by nooperation** [comment] 2022-02-15 20:53
This 100% sounds like someone is logging into your account and messing with you. I would suggest changing your password and seeing if this issue stops

**Comment by gaveitatry2** [comment] 2022-02-16 01:38
No, I already changed my password like two days ago because I am returning to SL for the first time in 10 years.  And if someone wanted to mess with me, I'm sure they would think of better things to do like change my SL or RL Profile, not some checkboxes in the Interests tab.  And no one knows me.  Because I haven't played SL in over 10 years.

**Comment by gaveitatry2** [comment] 2022-02-17 20:59
**UPDATE:**

So I think that I found the issue.  While in Radegast, go to your Interests tab and uncheck all the boxes and type something that you want to do like "I want to fly."  Save and close your profile.  Now open it up again.  It will appear the same.  Now close it again.  Now open up some random profiles of other SL residents that you see Nearby.  Close their profiles.  Open up your profile.  Now the stuff you typed will be gone or replaced and there will be random boxes checked.  It's a Radegast thing and I don't get the point.  Like "ha ha"?  So hopefully I can keep my settings if I NEVER open up another SL resident's profile.  If not, then well, I give up.

**Comment by gaveitatry2** [comment] 2022-02-17 21:13
**UPDATE:**

A three second video that proves Radegast is doing this.

https://youtu.be/MIVqdz6eJWs

**Comment by nooperation** [comment] 2022-02-17 21:31
Confirmed for radegast-ng

It looks like the interests tab is a new feature of the new radegast project https://github.com/cinderblocks/radegast / [radegast.life](https://radegast.life/) and is a little buggy at the moment. Thanks for the report

**Comment by gaveitatry2** [comment] 2022-02-17 21:45
@nooperation - I deleted the video because I didn't like the way Cinderblocks was talking to me and one other person on the  radegast.life Radegast 2.38 page.  He was very condescending and rude to say the least.  You could be him on a different Github name.  I don't know.  And maybe I'm just being paranoid, but I am hoping that he won't be making fun of my SL profile, going to my SL home, or making fun of my RL.  I'm sure the video can still be seen though even though I deleted it.  The point is if you have confirmed the bug, please let him know that it has been confirmed.  Because he seems very much in denial and told me the following:

**"Radegast isn’t doing this to your Interests tab. Your problem lies elsewhere."**

**Comment by idgas01** [comment] 2022-02-17 21:52
By the way, is it possible that I am not using the right Radegast version?  Like maybe I am using the 2.38 from your GitHub, when I should be using the 2.38 from his GitHub.  His 2.38 is newer and different, right?

**Comment by gaveitatry2** [comment] 2022-02-17 22:14
He deleted all of my posts and my bug report on radegast.life  I have no way of knowing if he himself acknowledges the bug.  He doesn't seem the friendly type, and I am tempted to believe he deleted my posts out of spite and not because they were no longer relevant.  Oh well.  He is only hurting himself by being that kind of person.  He will regret it one day.  I just like reporting bugs that I find, but this bug isn't going to make or break my day.  I'm like the water.  I'll just flow around it.  I did my part.  I tried to make the bug known.  I was as nice and polite as humanly possible.  If God doesn't want me to be heard, so be it.  Time to move on.  Thanks for your time.  Have a great day.

**Comment by cinderblocks** [comment] 2022-02-18 01:14
This is been addressed in [Radegast v2.39](https://github.com/cinderblocks/radegast/releases/tag/2.39). Thank you @nooperation for the quick patch!

@idgas01 The details provided to reproduce the problem were helpful, albeit this is the wrong project to report bugs Radegast-ng bugs to. Your original report in the comments of a blog post were not helpful. Nor was linking this issue to an unrelated pull request in the Radegast-ng repository.

There is nothing personal, and I am powerless over your interpretation of terseness as condescension. As far as the issue tracker is concerned, your opinion of my personality (formed from two sentences you read) does not belong in a bug report, and further behavior like this will simply get you banned from further participation. Take it to SLUniverse or somewhere that drama and high horsing are appreciated. 

By the way, [your bug report was not deleted](https://radegast.life/bugs/radegast-is-changing-the-contents-of-my-profile-interests-tab/), and your blog comments were removed because they did not belong in a Release Notes post. Further, I am a woman not a "he"; engineers can be female too.

**Comment by gaveitatry2** [comment] 2022-02-18 04:27
Wow.

(sidesteps)

By the way, the reason I created a GitHub issue on this project and not one on your Hub is because I couldn't find the Issues tab.  All I saw was a Pull Requests tab.  I just wanted to say that in case someone wants to create a GitHub issue later on the right project.

![firefox_n9UAJ0V5ii](https://user-images.githubusercontent.com/75463665/154617188-3a2982b7-cba4-450b-adab-8234e81f2d4d.png)

As for everything else, I'll focus on the positive.  Thanks for your help and for the patch nooperation.  Thanks cinderblock for making a 2.39 with the patch.  Have a great day.  I probably won't be active on either GitHub or the radegast.life website as that was the only real issue I had with Radegast in over 10 years and it was a minor one.  I just wanted to know if there was something that I could do on my end to fix it.  And I'm really sorry for not "knowing enough" as I haven't played SL in around 10 years, and I did not immediately know or understand all the things that I needed to know.  And I didn't immediately supply all the right most helpful details.  I"m a human, so that stuff kinda takes me time.  I was able to do it in two tries though, I believe.  At least it didn't take a dozen.  Thanks and have a blessed year.

**Comment by gaveitatry2** [comment] 2022-02-18 04:44
Well there is one more tiny bug with Interests.  I noticed it earlier today, but didn't report it.

If all the boxes are unchecked and you check the Build checkbox and then close and reopen your profile, it will have a checkmark under Textures.  The program wants to decide some stuff for you.  But what if I wanted to have this instead:

I want to: Build

Skills: Architecture, Modeling, and Scripting.

It won't let me have that.  It wants...


I want to Build:

Skills: Textures


My workaround for this problem is leave ALL boxes unchecked.  But just thought I should let you guys know.  Last report, I promise.  (Unsubscribed)

**Closed as completed** 2022-03-04 19:39 UTC
